Home Page
estagio-2023/appcasas-ui pull request #6
Opened 2024-03-07 18:08 UTC by diogo-s4ntos

Home page done with bootstrap 5.

2024-03-07 23:53 UTC, Silva096 commented on src/app/home/home.component.html
> +            <img src="../../assets/home_page_icons/properties.png" alt="">
Uma sugestão de melhoria Diogo:

Podem ser criadas variáveis no Typescript (uma para cada icon) que devem conter o caminho da imagem.
Aqui no HTML, em vez de ter `src="image_path"` pode ter `src={{nome_da_variável}}`

Desta forma fica mais fácil gerir o path das imagens.

2024-03-08 00:13 UTC, Silva096 commented on src/app/home/home.component.css
> +.container{
Este css está a ser aplicado à class "container" o que significa que vais estar a alterar a class do boostrap.

Todas as div's que tiverem a class container, vão ser afetadas por este css e ainda que só tenhamos um container, mais vale prevenir problemas no futuro.

O mesmo se aplica aos restantes

2024-03-08 09:22 UTC, diogo-s4ntos commented on src/app/home/home.component.html
> +            <img src="../../assets/home_page_icons/properties.png" alt="">
Done.

2024-03-08 09:25 UTC, diogo-s4ntos commented on src/app/home/home.component.css
> +.container{
Done.

2024-03-08 15:31 UTC, jonathan-osorio approved these changes

2024-03-08 15:35 UTC, Silva096 commented on src/app/home/home.component.ts
> +  img: string,
Interface deve ser criada fora do home component.ts numa pasta própria para tal
Assim mantemos o codigo organizado

2024-03-08 15:38 UTC, jonathan-osorio approved these changes

2024-03-08 15:39 UTC, diogo-s4ntos commented on src/app/home/home.component.css
> +.col-sm{
Done.

2024-03-08 15:43 UTC, diogo-s4ntos commented on src/app/home/home.component.ts
> +  img: string,
Done.

2024-03-08 15:58 UTC, Silva096 commented on src/app/home/home.component.ts
> +  buttonsFirstLine: homeButtons[] = [
Esta estrutura não está correta, a minha sugestão passa pelo seguinte:

`{
	firstRow:[
	{
		title: "title",
		img: "imagePath
	},
	{
		title: "title",
		img: "imagePath
	}
	],
	
	secondRow: [{
		titlle: "title",
		img: "imgPath"
	},
	{
		titlle: "title",
		img: "imgPath"
	}]
}`

2024-03-08 15:59 UTC, Silva096 commented on src/app/home/home.component.html
> +    <div class="row">
Corrigir os NgFor.

Com a estrutura que sugeri, pretendo um ngFor que percorra as Rows e um ngFor que depois percorra o que está lá dentro.

2024-03-08 16:24 UTC, diogo-s4ntos commented on src/app/home/home.component.ts
> +  buttonsFirstLine: homeButtons[] = [
Done.

2024-03-08 16:24 UTC, diogo-s4ntos commented on src/app/home/home.component.html
> +    <div class="row">
Done.

2024-03-11 18:55 UTC, Silva096 commented on src/app/home/home.component.css
> +#colunas-firstLine, #colunas-secondLine{
"colunas" need to be translated

2024-03-11 18:55 UTC, Silva096 commented on src/app/home/home.component.css
> +#colunas-firstLine img, #colunas-secondLine img{
translation required

2024-03-11 18:56 UTC, Silva096 requested changes

2024-03-11 18:56 UTC, Silva096 commented on src/app/home/home.component.css
> +#colunas-firstLine p, #colunas-secondLine p{
translation required

2024-03-11 18:56 UTC, Silva096 commented on src/app/home/home.component.html
> +      <div class="col-sm" id="colunas-firstLine" *ngFor="let buttonFirstRow of row.firstRow">
id translation

2024-03-11 18:56 UTC, Silva096 commented on src/app/home/home.component.html
> +        <div class="col-sm" id="colunas-secondLine" *ngFor="let buttonSecondRow of row.secondRow">
translation required

2024-03-11 19:14 UTC, Silva096 commented on src/app/modules/home-butttons.ts
> +export interface homeButtons {
Please change folder name to "Models"

2024-03-11 20:40 UTC, diogo-s4ntos commented on src/app/home/home.component.css
> +#colunas-firstLine, #colunas-secondLine{
Done.

2024-03-11 20:40 UTC, diogo-s4ntos commented on src/app/home/home.component.css
> +#colunas-firstLine img, #colunas-secondLine img{
Done.

2024-03-11 20:41 UTC, diogo-s4ntos commented on src/app/home/home.component.css
> +#colunas-firstLine p, #colunas-secondLine p{
Done.

2024-03-11 20:41 UTC, diogo-s4ntos commented on src/app/home/home.component.html
> +      <div class="col-sm" id="colunas-firstLine" *ngFor="let buttonFirstRow of row.firstRow">
Done.

2024-03-11 20:41 UTC, diogo-s4ntos commented on src/app/home/home.component.html
> +        <div class="col-sm" id="colunas-secondLine" *ngFor="let buttonSecondRow of row.secondRow">
Done.

2024-03-11 20:43 UTC, diogo-s4ntos commented on src/app/modules/home-butttons.ts
> +export interface homeButtons {
Done

2024-03-11 21:01 UTC, Silva096 approved these changes

2024-03-11 21:26 UTC, merged